"""Guard: the README '## Tools' table matches the registered MCP tool surface.

The README is the front door: a reader decides whether this server is worth adding
from that table alone. Tool names here are generated by ``FastMCP.from_fastapi``
from each route's ``operation_id``, so adding a route silently adds a tool — and a
hand-maintained table would drift the moment it happened.

This test closes that gap: it parses the table out of the README and asserts its
tool names equal the server's registered tools exactly, using the same ``facade``
fixture as ``test_tool_names.py``. Adding a tool without documenting it fails CI.

See the GeneFoundry README Standard v1 (docs/README-STANDARD-v1.md in
genefoundry-router), Rule 6.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

README = Path(__file__).resolve().parents[2] / "README.md"

_TOOLS_TABLE_ROW = re.compile(r"^\|\s*`(?P<name>[a-z0-9_]+)`\s*\|")


def _readme_tool_names() -> set[str]:
    """Tool names listed in the README's '## Tools' table."""
    lines = README.read_text(encoding="utf-8").splitlines()

    try:
        start = lines.index("## Tools")
    except ValueError:  # pragma: no cover - defended by the assertion below
        return set()

    names: set[str] = set()
    for line in lines[start + 1 :]:
        if line.startswith("## "):  # next section: the table is over
            break
        match = _TOOLS_TABLE_ROW.match(line)
        if match:
            names.add(match.group("name"))
    return names


async def test_readme_tools_table_matches_registered_tools(facade: Any) -> None:
    registered = {t.name for t in await facade.list_tools()}
    assert registered, "no tools registered on the facade"

    documented = _readme_tool_names()
    assert documented, "no tools found in the README '## Tools' table"

    missing_from_readme = registered - documented
    stale_in_readme = documented - registered

    assert not missing_from_readme, (
        f"tools are registered but missing from the README '## Tools' table: "
        f"{sorted(missing_from_readme)} — document them (one row each)"
    )
    assert not stale_in_readme, (
        f"the README '## Tools' table lists tools that are not registered: "
        f"{sorted(stale_in_readme)} — remove the stale rows"
    )
    assert documented == registered
